### PR TITLE
Add initial support for re-initializing media elements upon selective refresh

### PR DESCRIPTION
**Pull request by westonruter**
This fixes an issue with the video and audio widgets where a change to the widget in the customizer causes the widgets to selectively refresh and then fail to re-initialize ME.js.

### CODE REVIEW

**Review by obenland — APPROVED** [review]
The `file_get_contents` feels icky, but it's only temporary, seems fine

**Comment by westonruter** [comment]
@obenland I agree that using the inline script feeling icky. What are your thoughts on the todo?

> If audio, first ensure that wp_audio_shortcode_library filters away mediaelement; if video, check wp_video_shortcode_library filters the same

I've never seem this in the wild, but let's say someone adds a plugin that does:

```php
add_filter( 'wp_video_shortcode_library', function(){ return 'some_other_library'; } );
add_filter( 'wp_audio_shortcode_library', function(){ return 'some_other_library'; } );
```

Now, this should result in MediaElement.js not being loaded. Maybe this is out of scope for the media widgets, but if I only override _one_ of the libraries then MediaElement.js still ends up initializing both of them since it uses this selector: `$( '.wp-audio-shortcode, .wp-video-shortcode' )`.

**Comment by obenland** [comment]
Yeah, I don't think that is something we should concern ourselves with in the context of this plugin.

Not sure how to best go about it either, truthfully

**Comment by westonruter** [comment]
@joemcgill Is `wp.mediaelement` wrong to do `$( '.wp-audio-shortcode, .wp-video-shortcode' )` if a user had filtered `wp_video_shortcode_library` or `wp_audio_shortcode_library` to not be `mediaelement`? It seems maybe the values for these filters should be exported to `_wpmejsSettings` and `wp.mediaelement.initialize()` should read from them when deciding whether `.wp-audio-shortcode` and/or `.wp-video-shortcode` should be included among the selector?

**Comment by joemcgill** [comment]
@westonruter I'm not familiar with the back-history for that filter, but your thinking makes sense to me. I think it would have been a fairly safe assumption that if you were filtering the MJS library that you were doing so globally, and not optionally within the same page/frame. A workaround would be to make sure the already initialized frame had the `.mejs-mediaelement` class on it or we could alternately create a generic `.mediaelement--loaded` class that would be looked for before reinitializing.

**Pull request merged**
