### PR TITLE
Update Buttons Flexbox

### PR DESCRIPTION
**Pull request by timmyc**
After looking at #15 - I decided to play with the flexbox setup on the buttons a bit.  This small change just keeps the buttons naturally sized in-lieu of growing to fit the entire space on the widget screen, and adds `flex-wrap` to handle any situations where long translations would cause the buttons to get too large for one line.

__Before__
before

select-before

__After__
edit-after

select-both

### CODE REVIEW

**Comment by westonruter** [comment]
In #24 I've suggested the image should be centered when it isn't the full width.

I think it is preferred if the buttons stretch the full width or 50% if there are two. Compare with the media control in the customizer:

image

**Comment by timmyc** [comment]
Gotcha, makes sense.  The Select Image button still feels pretty large to me - but perhaps a designer can chime in on the matter ;)  - I'll close this one out for now.

**Comment by westonruter** [comment]
You know what? You're right. In the customizer, when only one button is displayed it gets shown at the same width and floated to the right:

image

@melchoyce should this be replicated here?

The following has been reported in #29.

----

I can also see that we may be missing styling for the non-selected state, where we don't currently show that dashed border, though this seems to imply it is a drag-and-droppable region (which it isn't in core, yet per [#35827](https://core.trac.wordpress.org/ticket/35827)):

image

**Comment by timmyc** [comment]
From Slack convo, here are the widget states with right-aligned buttons /cc @melchoyce 

widgets_ _wordpress_develop_ _wordpress

**Comment by melchoyce** [comment]
Okay, yeah, definitely has to be left-aligned. Thanks @timmyc.

**Comment by westonruter** [comment]
@timmyc note that the image would be center-aligned. Also, there is now a placeholder dotted box now. I just updated from `master` so you should see that now. This will help with the buttons feeling orphaned on the right.

And what about designs for letting the buttons be 100% wide (when one button), and 50% wide if two? Or 50% wide always, with the Edit Image button hidden when no selection is made and the Select Image button floated to the right?

**Comment by timmyc** [comment]
@westonruter I'll rebase my branch and add some screen grabs for the other approaches too.

**Comment by timmyc** [comment]
Rebased - new screenshots aligned right, customizer:

customize__wordpress_develop_ _just_another_wordpress_site

customize__wordpress_develop_ _just_another_wordpress_site

Widget admin looks same as above - perhaps I'll add the dotted placeholder there.

**Comment by westonruter** [comment]
I still think having the buttons 50% wide feels more refined (like intentionally designed), and is inline with the customizer media control. When the buttons have different widths to me it feels not as sharp.

**Comment by timmyc** [comment]
Customizer, current for comparison with the intial design.

customize__wordpress_develop_ _just_another_wordpress_site

customize__wordpress_develop_ _just_another_wordpress_site

**Comment by melchoyce** [comment]
@westonruter What would you do in cases where the button label translation is longer than the width of the button?

**Comment by westonruter** [comment]
@melchoyce in that case it's the same situation as with the existing media control. Translators have to know the context and know the size of the string they choose. This could be indicated via the `translators` comment or via the `$context` parameter in the translation function. This is what we did for the “Hide Controls” label in [#38762](https://core.trac.wordpress.org/ticket/38762). See [r39214](https://core.trac.wordpress.org/changeset/39214).

**Comment by melchoyce** [comment]
Let's go with the 50%/100% width buttons, then, and consider re-examining this pattern in core.

**Comment by westonruter** [comment]
See #38.

**Pull request closed without merging**
