### PR TITLE
Fix Video Loop Issues

### LINKED ISSUE #130: video looping
Adding a [youtube video](https://www.youtube.com/watch?v=GPTY6l_PX5k) without doing any changes. Playing it, it loops at the end of the video. 
If I  edit the video and check "loop", it doesn't loop anymore, not even if I uncheck/check and save multiple times.

### PR DESCRIPTION
**Pull request by timmyc**
This is still in progress as I still have yet to find a solution for the YouTube looping.  This branch seeks to fix #130 - though.  While testing out the original report, I noticed that the loop issue was only happening on YouTube embeds, and not on Vimeo embeds.  But even when `loop` was true for Vimeo embeds - they were not looping in the rendered widget.

A fix for the vimeo issue can be seen in dddaa88 ( which apparently has made CI unhappy ).  By adding the `loop` query arg on the Vimeo url, the underlying iframe from Vimeo loops when expected to.  YouTube also supports this query arg ( https://developers.google.com/youtube/player_parameters ), but it appears that mediaelement is mangling with the YouTube embed url... because even when the logic in this branch adds the `loop` query arg appropriately, the iframe src that is subsequently rendered in the widget no longer has the argument:

customize__blog_ _wordpress_develop

If I manually add the `loop` query arg back into the iframe URL seen above, the YouTube video no longer loops.

### CODE REVIEW

**Comment by timmyc** [comment]
Related: https://github.com/mediaelement/mediaelement/issues/1851

and fixed in https://github.com/instructure/mediaelement/pull/17

And released in version 2.23.2 per https://github.com/instructure/mediaelement/blob/master/changelog.md

Version of mejs in trunk is 2.22.0

**Comment by obenland** [comment]
Maybe we should update the library in 4.8?

**Comment by timmyc** [comment]
I think it was talked about in the bug scrub today: https://core.trac.wordpress.org/ticket/39686

The issue is to upgrade to a new major version release, so not sure if we can push to do a minor bump to 2.x or not... fwiw any use of `wp_video_shortcode` with a YouTube video is also affected by this.  I need to circle back and see if we can mimic the editor embed flow instead since it isn't looping.

**Comment by obenland** [comment]
With mediaelement updated, would we still need this proposed change?

**Review by westonruter — APPROVED** [review]

**Pull request merged**
