### PR TITLE
Add edit media button #2

### PR DESCRIPTION
**Pull request by obenland**
See #11

### CODE REVIEW

**Comment by obenland** [comment]
This is not the way I was hoping it would turn out. :(

@adamsilverstein Would you mind if I added you as a collaborator and we continue working on this branch?

**Comment by obenland** [comment]
I just added you, I figured you could decline the invite if you didn't want to ;)

**Comment by obenland** [comment]
@westonruter To be able to remove captions in the control preview we'll need some other way to store the caption information, likely a hidden input. Given that we currently use the same function to render the component preview and the actual widget content, I'd suggest waiting with removing the caption visually until #17 is in and we have templates we can use?

**Comment by westonruter** [comment]
@obenland yes, I agree. The caption should be removed from the control preview. The caption can be rendered exclusively in the customizer preview frame. And yes, the `caption` and other fields need to be stored in hidden inputs, and an initial implementation of this is now in #17 and ready for initial review. Some more cleanup is needed. Also, it's focused on the image widget. The audio and video widgets are currently disabled.

**Pull request closed without merging**
